### PR TITLE
US2-T2-Frontend Import CSV file

### PR DESCRIPTION
**Pull request by Paciflow**
csv import file. Its a button, I think it needs a root to the overview page.

### CODE REVIEW

**Review by LouisChoiniere — CHANGES_REQUESTED** [review]
- Why is there a index, main, and app file in this commit. It looks like you created a new project within the `CSV_Import` folder.
- This frontend is not liked to the backend
- This branch is 6 commits late from main, please make branch up to date

**Review by LouisChoiniere — COMMENTED** [review]
Also, you should never reuse the same branch twice, after the PR is accepted merged you should delete the branch and create a new one for the next task. This is why the branch is out of date. Reusing the same branch is only looking for trouble.

**Comment by tinaw1412** [comment]
I connected csv upload with endpoints (still need testing) and rearranged some files, there's trouble showing csv upload component in team overview (need to fix), also We have to remove some unnecessary component like create teams since upload csv does the work for that (need to rearrange react components)

**Review by tinaw1412 — CHANGES_REQUESTED** [review]
I connected csv upload with endpoints (still need testing) and rearranged some files, there's trouble showing csv upload component in team overview (need to fix), also We have to remove some unnecessary component like create teams since upload csv does the work for that (need to rearrange react components)

**Review by LouisChoiniere — COMMENTED** [review]
To what page do I need to go to see the changes? I can't seem to find it to review it.

**Comment by tinaw1412** [comment]
> To what page do I need to go to see the changes? I can't seem to find it to review it.

CSVUpload.jsx in teacher and Team Overview

**Review by LouisChoiniere — APPROVED** [review]
Work correctly cleanup of the paparse extension could be node otherwise looks good

**Review by tinaw1412 — APPROVED** [review]

**Pull request merged**
